import os, sys, shutil

# Ensure we can import prepare.py
script_dir = os.path.dirname(os.path.realpath(__file__))
prepare_dir = os.path.join(script_dir, 'Telegram', 'build', 'prepare')
sys.path.append(prepare_dir)

# Mock environment for win64
os.environ['Platform'] = 'x64'
os.environ['QT'] = '6.11.0'
if 'qt6' not in sys.argv:
    sys.argv.append('qt6')

import prepare

def extract():
    target_dir = os.path.join(script_dir, 'build', 'scripts')
    if os.path.exists(target_dir):
        shutil.rmtree(target_dir)
    os.makedirs(target_dir)
    
    # In prepare.py, stages are already filtered for the current platform (win64)
    # because of the stage() function calls during import.
    for stage in prepare.stages:
        name = stage['name']
        commands = stage['commands']
        
        with open(os.path.join(target_dir, f'{name}.bat'), 'w', encoding='utf-8') as f:
            f.write(f"@echo off\n")
            f.write(f"rem Build script for {name} (Platform: win64)\n")
            f.write(f"rem Generated by extract_stages.py\n\n")
            
            # Setup environment variables similar to prepare.py
            f.write(f"set \"LIBS_DIR={prepare.libsDir}\"\n")
            f.write(f"set \"THIRDPARTY_DIR={prepare.thirdPartyDir}\"\n")
            f.write(f"set \"USED_PREFIX={prepare.usedPrefix}\"\n")
            f.write(f"set \"ROOT_DIR={prepare.rootDir}\"\n")
            f.write(f"set \"X8664=x64\"\n")
            f.write(f"set \"SPECIAL_TARGET=win64\"\n")
            f.write(f"set \"PATH={prepare.pathPrefix}%PATH%\"\n\n")
            
            f.write(commands.strip())
            f.write("\n")
    
    print(f"Extracted {len(prepare.stages)} stages to {target_dir}")

if __name__ == '__main__':
    extract()
